/* eslint-disable react/jsx-no-undef */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import Carousel from 'react-bootstrap/Carousel';
import Marquee from "react-fast-marquee";
import React, { useState, useEffect } from "react";
import Modal_Boostrap from 'react-bootstrap/Modal';
import Withdraw_money from './withdraw_money'
import Topup from './topuop'
import Game_select from './game_select'
import Promotions from './promotions'
import Contaxt from './contaxt'
import Link from 'next/link'
import { MDBRipple } from 'mdb-react-ui-kit';
import RegisterFrom from './signUp'
import CloseBtn from './prop/close_btn'
import Buble from './prop/bubble'
import Advert1 from './prop/advert1'
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Navbar_user1 from '@/components/navbar_user'



function Home_play() {

    const [show_promotions, setShow_promotions] = useState(false);
    const [show_withdraw, setShow_withdraw] = useState(false);
    const [show_topup, setShowtopup] = useState(false);
    const [show_game, setShow_game] = useState(false);
  
    const closeModal_topup = () => setShowtopup(false);
    const openModal_topup = () => setShowtopup(true);
  
    const closeModal_withdraw = () => setShow_withdraw(false);
    const openModal_withdraw = () => setShow_withdraw(true);
  
    const closeModal_promotions = () => setShow_promotions(false);
    const openModal_promotions = () => setShow_promotions(true);
  
    const closeModal_game = () => setShow_game(false);
    const openModal_game = () => setShow_game(true);
  
    return (
      <>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

      <Navbar_user1></Navbar_user1>

        
        <div className={styles.fly_box}>
            <Marquee gradient={false}> <a >ยินดีต้อนรับเข้าสู่เว็บไซต์ สล็อต คาสิโนออนไลน์ pgauto-108.com พร้อมระบบฝาก-ถอนออโต้ 10 วินาที พนันออนไลน์ อันดับหนึ่ง ให้บริการ สล็อต คาสิโนออนไลน์ เราให้บริการด้านการเดิมพันคาสิโนบนเว็บแบบครบวงจรตลอด 24ชม. </a> </Marquee>
          </div>
        <br></br>      <br></br>      <br></br>
  
        
        <div className={'container'}>
  
          <Buble></Buble>
  
          <Contaxt></Contaxt>
  
          
  
          <div className={styles.ctrl}>
  
  
            <div className={styles.game}>
  
  
            <div className='row '>
            <div className={styles.head_ctrl}>
            <Image className="img-fluid" src="/Logo.png" width={200} height={"75"} alt="logo"></Image>
            <br></br>
            <a>ขอต้อนรับ 0808681</a>
            <br></br>
            <b>0 Rewards</b>
            <a className={styles.play_btn} href="#"></a>
            </div>
            </div>
  
  
  
              <div className='row '>
  
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                    <img className="ctrlZoom img-fluid" src="/m1.png" alt="img1" ></img>
                  </div>
                </div>
  
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                    <img className="ctrlZoom img-fluid" src="/m2.png" alt="img1" ></img>
                  </div>
                </div>
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                    <img className="ctrlZoom img-fluid" src="/m3.png" alt="img1" ></img>
                  </div>
                </div>
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                  <img className="ctrlZoom img-fluid" src="/m4.png" alt="img1" ></img>
                </div>
                 </div>
                 
              </div>
  
  
              
              <div className='row '>
  
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                    <img className="ctrlZoom img-fluid" src="/m5.png" alt="img1" ></img>
    
                  </div>
               
                </div>
  
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                    <img className="ctrlZoom img-fluid" src="/m6.png" alt="img1" ></img>
 
                  </div>
                </div>
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                    <img className="ctrlZoom img-fluid" src="/m7.png" alt="img1" ></img>
         
                  </div>

                </div>
                <div className={styles.ctrl_box}>
                  <div className="col-4 boximgzoom ">
                  <img className="ctrlZoom img-fluid" src="/m8.png" alt="img1" ></img>
    
                </div>

                 </div>
                 
              </div>
              
    
  
  
  
            </div>
  
  
          </div>
  
  
  
  
  
        </div>
        <Footer></Footer>
        <div id="root"></div>
      </>)
  
  }
export default Home_play